# Generated by Django 5.2.17 on 2026-08-21 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Encerrada')], default='OPEN', max_length=10)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='whatsapp_chat.contact')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Recebida'), ('OUT', 'Enviada')], max_length=3)),
                ('message_type', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('DOCUMENT', 'Documento'), ('AUDIO', 'Áudio'), ('OTHER', 'Outro')], default='TEXT', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('wa_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebida'), ('SENT', 'Enviada'), ('DELIVERED', 'Entregue'), ('READ', 'Lida'), ('FAILED', 'Falhou')], max_length=10)),
                ('error_detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_chat.conversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
