# Generated by Django 5.2.17 on 2026-08-21 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADA', 'Reservada'), ('BLOQUEADA', 'Bloqueada')], default='RESERVADA', max_length=20, verbose_name='Status')),
                ('event_type', models.CharField(blank=True, choices=[('CASAMENTO', 'Casamento'), ('FESTA_15_ANOS', 'Festa de 15 Anos'), ('CHA_DE_BEBE', 'Chá de Bebê'), ('NOIVADO', 'Noivado'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de evento')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do cliente')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do cliente')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
